name: Exploring Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: pradyaiml
    IMAGE_NAME: github-actions01

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t ${{ env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:101

            - name: Docker Login
              run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: Docker Publish
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:101


    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:101